# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master


stages:
  - stage: Build
    displayName: Build Package
    jobs: 
    - job: BuildPackage
      pool: MyLocalMachine
      steps:    
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)'
          outputType: 'Process'
          orchestratorConnection: 'UiPath Connection'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: DeployDEV
    displayName: Deploy build artifact to DEV
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeplayDEV
        displayName: Deploy package to Orchestrator
        pool: MyLocalMachine
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: 'UiPath Connection'
                packagesPath: '$(Pipeline.Workspace)\drop\'
                entryPoints: 'Main.xaml'
                folderName: 'RenuIT'
  
  - stage: Execute
    displayName: Execute the process
    dependsOn: 
    condition: 
    jobs:
      - job: ExecuteCode
        pool: MyLocalMachine
        steps:
        - task: UiPathRunJob@2
          inputs:
            orchestratorConnection: 'UiPath Connection'
            processName: 'GitPipeline_3_Main.xaml'
            folderName: 'RenuIT'
